# Materialise the crop-specific pre-1962 land proxy the cell-level back-cast
# consumes.
#
# `build_cell_crop_land()` spatializes 1961 and then rescales ~1.25 million
# cell-crop rows once per back-cast year, so a full run is a couple of minutes
# of work over a gigabyte of intermediates. The result is STATIC -- it depends
# only on the LUH2 vintage, the crop patterns, the polycell support and the
# polities snapshot, none of which moves between builds -- so it is computed
# once here rather than inside every
# `build_primary_production(land_method = "cell_polity")` call.
#
# Like `data-raw/historical_land_areas.R`, this writes a parquet rather than a
# `data/*.rda`: it is an INPUT to the pipeline, not a harmonisation table, so
# its home is the pins board `whep_inputs.csv` indexes. Until it is published,
# point `WHEP_CELL_CROP_LAND_PATH` at the parquet.
#
# REGENERATE THE CROP PATTERNS FIRST. `earthstat_mapping.csv` shipped with no
# `barley`, `greencorn` or `hempseed` row, so the `spatialize-crop-patterns` pin
# carries no cells for them and this table cannot back-cast them at all. Barley
# alone is 5.7% of the world's 1961 harvested area. The crosswalk is fixed in
# this repo; the pin is regenerated by
# `inst/scripts/prepare_spatialize_all.R`'s `prepare_crop_patterns()`.
#
# Provenance to record with the pin:
#   * The `spatialize-crop-patterns` and `spatialize-gridded-cropland` pin
#     versions, from `whep::whep_inputs`. The first decides which cells grow
#     which crop; the second is both halves of every ratio.
#   * The `polycell_support` pin version, which decides which cells each polity
#     holds. A polity absent from it is a bucket absent from the result, so the
#     two pins must be refreshed in that order: polycell first, then this one.
#   * The `polities` snapshot -- `max(whep::polities$last_ingest)`.
#
# Usage:
#   Rscript --vanilla data-raw/cell_crop_land.R [out_path]

devtools::load_all(here::here(), quiet = TRUE)

args <- commandArgs(trailingOnly = TRUE)
out_path <- if (length(args) > 0L) {
  args[[1]]
} else {
  here::here("data-raw", "cell_crop_land.parquet")
}

land <- whep::build_cell_crop_land(years = 1850:1961)

cli::cli_alert_info(
  "{nrow(land)} row{?s}, {dplyr::n_distinct(land$area_code)} bucket{?s},
   {dplyr::n_distinct(land$item_prod_code)} crop{?s},
   {min(land$year)}-{max(land$year)}."
)

arrow::write_parquet(land, out_path)
cli::cli_alert_success("Wrote {.file {out_path}}.")
