#' Bilateral trade data
#'
#' @description
#' Clean CSV data from the given `file_path`. It is recommended to use an
#' autogenerated path by `get_file_path()` function.
#'
#' @param file_path The local path where the input CSV is located
#'
#' @returns
#' A tibble with the reported trade between countries.
#' It contains the following columns:
#' - `year`: The year in which the recorded event occurred.
#' - `from_code`: FAOSTAT internal code for the country that is exporting the
#'    item. Equivalences with ISO 3166-1 numeric can be found in the
#'    _Area Codes_ CSV from the zip file that can be downloaded from
#'    [FAOSTAT](https://www.fao.org/faostat/en/#data/FBS). TODO: Think about
#'    this, would be nice to use ISO3 codes but won't be enough for our periods
#' - `to_code`: FAOSTAT internal code for the country that is importing the
#'    item. See previous `from_code`.
#' - `item`: Natural language name for the item that is being traded.
#' - `unit`: Measure unit for the traded item. It can have two values:
#'      - `"tonnes"`: Trade amount in tonnes (for crop and livestock products)
#'      - `"heads"`: Trade amount in number of animals (for live animal items)
#' - `value`: The amount traded in the corresponding measure unit.
#'
#' For the final data obtained, the export data was preferred, i.e.,
#' if country `"A"` says it exported `X` tonnes to country `"B"` but country
#' `"B"` claims they got `Y` tonnes from country `"A"`, we trust the export data
#' `X`. This choice is only needed if there exists a reported amount from both
#' sides. Otherwise, the single existing report is chosen.
#'
#' For each item and year, the total exports should match the total imports.
#' TODO: Balance data for this to be true.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' get_bilateral_trade(get_file_path("bilateral_trade"))
#' }
get_bilateral_trade <- function(file_path) {
  file_path |>
    readr::read_csv() |>
    dplyr::rename_with(tolower) |>
    dplyr::mutate(
      unit = ifelse(unit == "Head", "heads", unit),
      from_code = ifelse(element == "Export", area_code, area_code_p),
      to_code = ifelse(element == "Export", area_code_p, area_code),
    ) |>
    prefer_flow_direction("Export") |>
    dplyr::select(year, from_code, to_code, item, unit, value)
}

# Keep all rows with preferred direction (Import, Export)
# when both of them exist. Otherwise use the one present.
prefer_flow_direction <- function(bilateral_trade, direction) {
  preferred_direction <- dplyr::filter(bilateral_trade, element == direction)

  bilateral_trade |>
    dplyr::anti_join(
      preferred_direction,
      by = c("from_code", "to_code", "year", "item")
    ) |>
    dplyr::bind_rows(preferred_direction)
}
