# The SJOS-N nourishment floor: the four-term replacement for the unsourced
# 1.35 multiplier (whep#753).
#
# The model is WHO/FAO/UNU TRS 935 Box 1 (p.44), NOT FAO's PoU inversion, and
# the choice is forced rather than preferred:
#
#   1. FAO's inversion needs the class MINIMUM requirement. TRS 935 publishes no
#      lower-bound protein requirement per class, so the slot cannot be filled
#      without inventing one.
#   2. FAO's PoU is a cut-point method, and IOM Box 4-2 condition 4 requires
#      true prevalence >= 8-10%. Every target here is 2.5-10%. Box 1's exact
#      convolution carries no such condition.
#   3. FAO's within-requirement CV is generated by a physical-activity gap.
#      TRS 935's protein requirement is per kilogram of body weight and carries
#      no activity term, so importing it would import a variance with no protein
#      analogue.
#
# Box 1, verbatim: "If log(requirement) is normally distributed with mean M_R
# and standard deviation S_R and log(intake) is normally distributed with mean
# M_I and standard deviation S_I with correlation = R, then log(deficit) =
# log(intake) - log(requirement) is normally distributed with mean M_D = M_I -
# M_R and standard deviation S_D = square root of (S_I^2 + S_R^2 - 2 R S_I
# S_R)." Prevalence of deficit is then Phi(-M_D / S_D).
#
# THE ANCHOR IS THE AVERAGE REQUIREMENT, NOT THE SAFE LEVEL, and that too is
# the source's instruction rather than a preference:
#
#   p.41   "reference intake or safe intake levels defined as above for
#           individuals have been incorrectly applied to populations."
#   p.241  "For a population, a safe population intake cannot be defined as a
#           simple function of the mean requirement."
#
# With the average anchor the requirement margin appears exactly once, inside
# S_R. Feeding the safe level in instead counts it twice, which is why that
# case warns here.

#' Build the SJOS-N nourishment floor.
#'
#' @description
#' Returns the threshold on **mean per-capita protein supply** below which a
#' country-year is under-nourished, composed from the terms that replace the
#' unsourced 1.35 multiplier (whep#753). Per country `c` and year `t`:
#'
#' \deqn{S_D = \sqrt{S_I^2 + S_R^2}}
#' \deqn{F = \bar{R} \cdot
#'   \exp(z_{1-p} S_D + S_I^2/2) / (1 - \omega)}
#'
#' `R̄` is the demographically weighted **average** requirement from
#' [build_protein_requirement()], `S_I` the within-country log-scale intake
#' dispersion from [build_intake_dispersion()], and `omega` the supply-to-intake
#' wedge from [build_loss_wedge()]. `S_R` is the log-scale spread of the
#' requirement itself.
#'
#' Two terms in that product are easy to drop and both are signed:
#' `exp(z * S_D)` carries the median requirement to the required median intake
#' at the tolerated shortfall, and `exp(S_I^2/2)` carries a required median to a
#' required **mean**, which is what makes the floor comparable with a per-capita
#' supply figure at all. Omitting the second is not conservative — it sets the
#' required mean equal to the required median, about 5% too low at a typical
#' dispersion.
#'
#' `shortfall` is the tolerated prevalence of inadequacy, 2.5% by default, and
#' that value is not a free choice: TRS 935 Figure 7 is headed "Safe population
#' intake ie. risk<2.5%", and FAO separately calls 2.5% "the lowest feasible
#' target that can be set for the PoU indicator". Departing from it is the
#' science decision; adopting it follows the source.
#'
#' **The protein-quality term is not built, and the floor is a known
#' understatement without it.** TRS 935 defines its safe level "for proteins
#' with a PDCAAS value of 1.0" (section 14.2); real national diets score below
#' 1.0, so a quality-adjusted floor is higher, by a level shift the evidence
#' record puts at +11% to +36%. `quality = "none"` is therefore stamped in
#' `method_quality` rather than left implicit, and the method name will not
#' silently change meaning when the term lands.
#'
#' Supplying `data$supply` adds `prevalence_protein_deficit`, the internal
#' quantity the floor inverts:
#' \eqn{\Phi(-(\log(\mathrm{supply}(1-\omega)) - S_I^2/2 - \log\bar{R})/S_D)}.
#' At `supply = floor` it returns `shortfall` exactly, which is the round trip
#' the tests pin.
#'
#' @param data Named list of injected inputs. `requirement` (`year`,
#'   `area_code`, `requirement_g_cap_day`), `dispersion` (`year`, `area_code`,
#'   `sigma`) and `loss_wedge` (`year`, `area_code`, `omega`) are required;
#'   optional `supply` (`year`, `area_code`, `protein_g_cap_day`) adds the
#'   prevalence column.
#' @param shortfall Tolerated prevalence of inadequacy, in `(0, 1)`. Defaults to
#'   `0.025`.
#' @param quality Protein-quality adjustment. Only `"none"` exists so far; see
#'   the description for what its absence costs.
#' @param requirement_sd Log-scale SD of the requirement, `S_R`. Defaults to
#'   `0.12`, TRS 935 p.38 for adults on a per-kilogram basis. The report notes
#'   this captures only about a fifth of observed between-individual variance,
#'   so it is exposed for sensitivity rather than fixed.
#' @return A tibble keyed by `year`, `area_code` with `floor_g_cap_day`,
#'   `requirement_g_cap_day`, `sigma_intake`, `sigma_deficit`, `omega`,
#'   `method_quality` and `method_shortfall`, plus `prevalence_protein_deficit`
#'   when `data$supply` is given, and the polity columns below.
#' @inheritSection whep_polity_columns Polity columns
#' @export
#' @examples
#' build_nourishment_floor(
#'   data = list(
#'     requirement = tibble::tribble(
#'       ~year, ~area_code, ~requirement_g_cap_day,
#'       2010L, 10L,        50
#'     ),
#'     dispersion = tibble::tribble(
#'       ~year, ~area_code, ~sigma,
#'       2010L, 10L,        0.25
#'     ),
#'     loss_wedge = tibble::tribble(
#'       ~year, ~area_code, ~omega,
#'       2010L, 10L,        0.025
#'     )
#'   )
#' )
build_nourishment_floor <- function(
  data = list(),
  shortfall = 0.025,
  quality = "none",
  requirement_sd = 0.12
) {
  quality <- rlang::arg_match(quality)
  .nf_check_shortfall(shortfall)
  terms <- .nf_join_terms(data)
  .nf_warn_safe_anchor(data$requirement)

  terms |>
    .nf_compose(shortfall, requirement_sd) |>
    .nf_add_prevalence(data$supply, requirement_sd) |>
    dplyr::mutate(
      method_quality = quality,
      method_shortfall = shortfall
    ) |>
    .add_reporting_polity_columns()
}

# ---- Private helpers -------------------------------------------------------

# S_D = sqrt(S_I^2 + S_R^2), the R = 0 case of Box 1. TRS 935 sets the
# correlation to zero explicitly ("assuming that intake and requirement, both
# expressed on a per kg body weight basis, are not correlated"), and Table 2 is
# headed "Zero correlation assumed". It is an assumption, not a measurement: a
# positive correlation would shrink S_D and lower every floor.
.nf_deficit_sd <- function(sigma_intake, requirement_sd) {
  sqrt(sigma_intake^2 + requirement_sd^2)
}

# Prevalence of deficit, Phi(-M_D / S_D).
.nf_prevalence <- function(m_d, s_d) {
  stats::pnorm(-m_d / s_d)
}

.nf_check_shortfall <- function(shortfall) {
  ok <- rlang::is_scalar_double(shortfall) &&
    is.finite(shortfall) &&
    shortfall > 0 &&
    shortfall < 1
  if (!ok) {
    cli::cli_abort(
      "{.arg shortfall} must be one number strictly between 0 and 1, not
       {.val {shortfall}}."
    )
  }
}

# Full-outer over the three terms, so a country-year missing one of them keeps
# a row with an NA floor instead of disappearing from the output. A gap that is
# absent from the table cannot be counted.
.nf_join_terms <- function(data) {
  requirement <- .nf_take(
    data$requirement,
    "requirement_g_cap_day",
    "data$requirement"
  )
  dispersion <- .nf_take(data$dispersion, "sigma", "data$dispersion")
  loss_wedge <- .nf_take(data$loss_wedge, "omega", "data$loss_wedge")
  requirement |>
    dplyr::full_join(dispersion, by = c("year", "area_code")) |>
    dplyr::full_join(loss_wedge, by = c("year", "area_code"))
}

.nf_take <- function(table, value, arg) {
  if (is.null(table)) {
    cli::cli_abort("{.field {arg}} is required.")
  }
  .check_columns(table, c("year", "area_code", value), arg)
  dplyr::select(table, dplyr::all_of(c("year", "area_code", value)))
}

.nf_compose <- function(terms, shortfall, requirement_sd) {
  z <- stats::qnorm(1 - shortfall)
  dplyr::transmute(
    terms,
    year = .data$year,
    area_code = .data$area_code,
    requirement_g_cap_day = .data$requirement_g_cap_day,
    sigma_intake = .data$sigma,
    sigma_deficit = .nf_deficit_sd(.data$sigma, requirement_sd),
    omega = .data$omega,
    floor_g_cap_day = .data$requirement_g_cap_day *
      exp(z * .data$sigma_deficit + .data$sigma^2 / 2) /
      (1 - .data$omega)
  )
}

# The prevalence the floor inverts. Kept optional because it needs a supply the
# floor itself does not: the floor is a threshold, not a measurement.
.nf_add_prevalence <- function(floor, supply, requirement_sd) {
  if (is.null(supply)) {
    return(floor)
  }
  .check_columns(
    supply,
    c("year", "area_code", "protein_g_cap_day"),
    "data$supply"
  )
  floor |>
    dplyr::left_join(
      dplyr::select(
        supply,
        "year",
        "area_code",
        "protein_g_cap_day"
      ),
      by = c("year", "area_code")
    ) |>
    dplyr::mutate(
      prevalence_protein_deficit = .nf_prevalence(
        log(.data$protein_g_cap_day * (1 - .data$omega)) -
          .data$sigma_intake^2 / 2 -
          log(.data$requirement_g_cap_day),
        .data$sigma_deficit
      )
    ) |>
    dplyr::select(-"protein_g_cap_day")
}

# The safe level already carries a 97.5th-percentile individual margin. Adding
# this formula's own population margin on top counts it twice, which is the
# construction TRS 935 p.41 and p.241 forbid outright.
.nf_warn_safe_anchor <- function(requirement) {
  if (!rlang::has_name(requirement, "method_requirement")) {
    return(invisible())
  }
  if (!any(requirement$method_requirement == "safe", na.rm = TRUE)) {
    return(invisible())
  }
  cli::cli_warn(c(
    "!" = "The requirement is stamped {.val safe}, which already carries an
           individual 97.5th-percentile margin.",
    "i" = "This floor adds its own population margin over {.arg requirement_sd},
           so the margin is counted twice.",
    "i" = "TRS 935 p.41 calls applying an individual safe level to a population
           incorrect; use {.code requirement = \"average\"} and vary
           {.arg requirement_sd} for sensitivity instead."
  ))
}
