# The SJOS-N nourishment band: the sourced replacement for a flat 46 x 1.35
# floor and a flat 63 x 1.35 ceiling (whep#753).
#
# The model is WHO/FAO/UNU TRS 935 Box 1 (p.44), NOT FAO's PoU inversion, and
# the choice is forced rather than preferred:
#
#   1. FAO's inversion needs the class MINIMUM requirement. TRS 935 publishes no
#      lower-bound protein requirement per class, so the slot cannot be filled
#      without inventing one.
#   2. FAO's PoU is a cut-point method, and IOM Box 4-2 condition 4 requires
#      true prevalence >= 8-10%. Every target here is 2.5-10%. Box 1's exact
#      convolution carries no such condition.
#   3. FAO's within-requirement CV is generated by a physical-activity gap.
#      TRS 935's protein requirement is per kilogram of body weight and carries
#      no activity term, so importing it would import a variance with no protein
#      analogue.
#
# Box 1, verbatim: "If log(requirement) is normally distributed with mean M_R
# and standard deviation S_R and log(intake) is normally distributed with mean
# M_I and standard deviation S_I with correlation = R, then log(deficit) =
# log(intake) - log(requirement) is normally distributed with mean M_D = M_I -
# M_R and standard deviation S_D = square root of (S_I^2 + S_R^2 - 2 R S_I
# S_R)." Prevalence of deficit is then Phi(-M_D / S_D).
#
# BOTH BOUNDS ARE THE SAME INVERSION of that one distribution, differing only in
# the anchor and the tolerated share. Each bound is its anchor, times the
# exponential of (z times S_D plus half S_I squared), divided by one minus
# omega, where:
#
#   floor    anchor is the AVERAGE requirement,   z is qnorm(1 - shortfall)
#   ceiling  anchor is multiple x the SAFE level, z is qnorm(share)
#
# THE TWO TAILS DO NOT CARRY THE SAME TOLERANCE, and the model says so rather
# than the author choosing it. Demanding that only 2.5% exceed the upper limit,
# mirroring the floor's shortfall, puts the ceiling BELOW the floor for 162 of
# 167 country-years on the 2010 build. That is the arithmetic reflecting TRS
# 935's own asymmetry: falling below requirement is harmful, while twice the
# safe level is "unlikely to be associated with any risk" (s14.2). At the
# default share of 0.5 the band never inverts -- the lowest ceiling (74.81)
# still exceeds the highest floor (73.75).

#' Build the SJOS-N nourishment band.
#'
#' @description
#' Returns the floor and ceiling on **mean per-capita protein supply** that
#' bound the adequate band, the prevalence of inadequacy and of excess, and the
#' number of people on each side. It replaces a flat 46 x 1.35 floor and a flat
#' 63 x 1.35 ceiling, of which only the 46 was ever sourced (whep#753).
#'
#' Both bounds are one inversion of the WHO/FAO/UNU TRS 935 Box 1 lognormal:
#'
#' \deqn{S_D = \sqrt{S_I^2 + S_R^2}}
#' \deqn{\mathrm{bound} = \mathrm{anchor} \cdot
#'   \exp(z S_D + S_I^2/2) / (1 - \omega)}
#'
#' The **floor** anchors on the demographically weighted *average* requirement
#' with \eqn{z = \Phi^{-1}(1 - \mathrm{shortfall})}: the supply below which more
#' than `shortfall` of the population falls short. The **ceiling** anchors on
#' `multiple` times the demographically weighted *safe level* with
#' \eqn{z = \Phi^{-1}(\mathrm{share})}: the supply above which more than `share`
#' of the population exceeds that limit.
#'
#' `exp(z S_D)` carries a median anchor to the required median intake, and
#' `exp(S_I^2/2)` carries a median to a **mean**, which is what makes either
#' bound comparable with a per-capita supply figure. Omitting the second is not
#' conservative — it sets the required mean equal to the required median, about
#' 5% too low at a typical dispersion.
#'
#' **The two tails do not take the same tolerance, and that is the model's
#' finding rather than a preference.** `shortfall` defaults to 2.5%, fixed
#' independently by TRS 935 Figure 7 ("Safe population intake ie. risk<2.5%")
#' and by FAO's stated lowest feasible PoU target. Applying 2.5% to the upper
#' tail as well puts the ceiling *below* the floor for 162 of 167 country-years
#' on the 2010 build, because TRS 935 calls intakes below requirement harmful
#' while calling twice the safe level "unlikely to be associated with any risk"
#' (section 14.2).
#'
#' **`share` is WHEP's own criterion, not a sourced value, and it is the only
#' number in the band that is.** It defaults to 0.5, which reads "Over" as *the
#' typical member of this population exceeds the limit* — a definition of
#' over-nourishment, not a measurement of harm. Where `shortfall` is fixed
#' independently by TRS 935 Figure 7 and by FAO's PoU target, nothing external
#' fixes `share`: TRS 935 declines to set a tolerable upper intake at all. It is
#' exposed precisely so it can be varied, the chosen value is stamped in
#' `method_ceiling`, and any published use should carry a sensitivity across it.
#' The `people_over` column exists partly for this reason: reported as a
#' continuous headcount, the result does not rest on where the class boundary
#' was drawn.
#'
#' `multiple` defaults to 2, which TRS 935 section 13.7 names as "twice the
#' recommended intake, previously identified as a safe upper limit ... likely to
#' be safe". The report's own alternative is 3–4x, which it says "approach the
#' tolerable upper limit and cannot be assumed to be risk-free"; both stay
#' selectable and the choice is stamped in `method_ceiling`.
#'
#' **Protein quality divides BOTH bounds**, which is algebraically the diet-side
#' correction TRS 935 section 14.1.5 prefers: comparing `supply x q` against a
#' crude bound and comparing crude supply against `bound / q` are the same
#' inequality, and dividing both keeps the published supply series untouched
#' while moving the floor and the ceiling together. Correcting only the floor
#' would leave the ceiling on crude protein and put the two bounds on different
#' bases. Supply `data$quality` from [build_protein_quality()]; without it the
#' band stays on crude protein and `method_quality` says `"none"`, which is a
#' known understatement of 11-36%.
#'
#' Supplying `data$supply` adds the prevalences and, where a population is
#' available, the headcounts. A country is not uniformly under or over: with a
#' supply inside the band both tails are populated, and `people_under` /
#' `people_over` are the quantities that say by how much.
#'
#' @param data Named list of injected inputs. `requirement` (`year`,
#'   `area_code`, `requirement_g_cap_day`, optionally `population`),
#'   `requirement_safe` (the same from [build_protein_requirement()] with
#'   `requirement = "safe"`), `dispersion` (`year`, `area_code`, `sigma`) and
#'   `loss_wedge` (`year`, `area_code`, `omega`) are required; optional `supply`
#'   (`year`, `area_code`, `protein_g_cap_day`, optionally `population`) adds
#'   the prevalence and headcount columns, and optional `quality` (`year`,
#'   `area_code`, `quality`) from [build_protein_quality()] divides both
#'   bounds.
#' @param shortfall Tolerated prevalence of inadequacy, in `(0, 1)`. Defaults to
#'   `0.025`.
#' @param ceiling Named list with `multiple` (of the safe level, positive;
#'   defaults to `2`) and `share` (tolerated prevalence of excess, in `(0, 1)`;
#'   defaults to `0.5`).
#' @param requirement_sd Log-scale SD of the requirement, `S_R`. Defaults to
#'   `0.12`, TRS 935 p.38 for adults on a per-kilogram basis. The report notes
#'   this captures only about a fifth of observed between-individual variance,
#'   so it is exposed for sensitivity rather than fixed.
#' @return A tibble keyed by `year`, `area_code` with `floor_g_cap_day`,
#'   `ceiling_g_cap_day`, `requirement_g_cap_day`, `safe_g_cap_day`,
#'   `sigma_intake`, `sigma_deficit`, `omega`, `quality`, `method_quality`,
#'   `method_shortfall` and `method_ceiling`; plus
#'   `prevalence_protein_deficit`, `prevalence_protein_excess`, `people_under`
#'   and `people_over` when `data$supply` is given; plus the polity columns
#'   below.
#' @inheritSection whep_polity_columns Polity columns
#' @export
#' @examples
#' build_nourishment_band(
#'   data = list(
#'     requirement = tibble::tribble(
#'       ~year, ~area_code, ~requirement_g_cap_day,
#'       2010L, 10L,        32
#'     ),
#'     requirement_safe = tibble::tribble(
#'       ~year, ~area_code, ~requirement_g_cap_day,
#'       2010L, 10L,        40
#'     ),
#'     dispersion = tibble::tribble(
#'       ~year, ~area_code, ~sigma,
#'       2010L, 10L,        0.26
#'     ),
#'     loss_wedge = tibble::tribble(
#'       ~year, ~area_code, ~omega,
#'       2010L, 10L,        0.025
#'     )
#'   )
#' )
build_nourishment_band <- function(
  data = list(),
  shortfall = 0.025,
  ceiling = list(multiple = 2, share = 0.5),
  requirement_sd = 0.12
) {
  .nf_check_shortfall(shortfall)
  ceiling <- .nb_check_ceiling(ceiling)
  terms <- .nb_join_terms(data)
  .nf_warn_safe_anchor(data$requirement)

  terms |>
    .nb_compose(shortfall, ceiling, requirement_sd) |>
    .nb_apply_quality(data$quality) |>
    .nb_add_prevalence(data, ceiling) |>
    dplyr::mutate(
      method_shortfall = shortfall,
      method_ceiling = sprintf(
        "%gx_safe_level_at_%gpct",
        ceiling$multiple,
        100 * ceiling$share
      )
    ) |>
    .add_reporting_polity_columns()
}

# ---- Private helpers -------------------------------------------------------

# S_D = sqrt(S_I^2 + S_R^2), the R = 0 case of Box 1. TRS 935 sets the
# correlation to zero explicitly ("assuming that intake and requirement, both
# expressed on a per kg body weight basis, are not correlated"), and Table 2 is
# headed "Zero correlation assumed". It is an assumption, not a measurement: a
# positive correlation would shrink S_D and narrow the band from both sides.
.nf_deficit_sd <- function(sigma_intake, requirement_sd) {
  sqrt(sigma_intake^2 + requirement_sd^2)
}

# Prevalence of deficit, Phi(-M_D / S_D).
.nf_prevalence <- function(m_d, s_d) {
  stats::pnorm(-m_d / s_d)
}

.nf_check_shortfall <- function(shortfall) {
  if (!.nb_is_fraction(shortfall)) {
    cli::cli_abort(
      "{.arg shortfall} must be one number strictly between 0 and 1, not
       {.val {shortfall}}."
    )
  }
}

.nb_is_fraction <- function(x) {
  rlang::is_scalar_double(x) && is.finite(x) && x > 0 && x < 1
}

.nb_check_ceiling <- function(ceiling) {
  .check_columns(ceiling, c("multiple", "share"), "ceiling")
  if (!.nb_is_fraction(ceiling$share)) {
    cli::cli_abort(
      "{.field ceiling$share} must be one number strictly between 0 and 1, not
       {.val {ceiling$share}}."
    )
  }
  ok_multiple <- rlang::is_scalar_double(ceiling$multiple) &&
    is.finite(ceiling$multiple) &&
    ceiling$multiple > 0
  if (!ok_multiple) {
    cli::cli_abort(
      "{.field ceiling$multiple} must be one positive number, not
       {.val {ceiling$multiple}}."
    )
  }
  ceiling
}

# Full-outer over the four terms, so a country-year missing one of them keeps a
# row with an NA band instead of disappearing. A gap that is absent from the
# table cannot be counted.
.nb_join_terms <- function(data) {
  average <- .nf_take(
    data$requirement,
    "requirement_g_cap_day",
    "data$requirement"
  )
  safe <- .nf_take(
    data$requirement_safe,
    "requirement_g_cap_day",
    "data$requirement_safe"
  ) |>
    dplyr::rename(safe_g_cap_day = "requirement_g_cap_day")
  dispersion <- .nf_take(data$dispersion, "sigma", "data$dispersion")
  loss_wedge <- .nf_take(data$loss_wedge, "omega", "data$loss_wedge")
  average |>
    dplyr::full_join(safe, by = c("year", "area_code")) |>
    dplyr::full_join(dispersion, by = c("year", "area_code")) |>
    dplyr::full_join(loss_wedge, by = c("year", "area_code"))
}

.nf_take <- function(table, value, arg) {
  if (is.null(table)) {
    cli::cli_abort("{.field {arg}} is required.")
  }
  .check_columns(table, c("year", "area_code", value), arg)
  .nb_check_unique(table, arg)
  dplyr::select(table, dplyr::all_of(c("year", "area_code", value)))
}

# Every input must be one row per country-year. A table that is not -- an item
# dimension left in, say -- fans the band out on the join and multiplies the
# headcounts by the number of duplicate keys, silently and by a factor nobody
# would think to look for. Found doing exactly that with FAOSTAT element 674,
# which is published per item.
.nb_check_unique <- function(table, arg) {
  keys <- dplyr::select(table, "year", "area_code")
  extra <- nrow(keys) - nrow(dplyr::distinct(keys))
  if (extra == 0L) {
    return(invisible())
  }
  cli::cli_abort(c(
    "{.field {arg}} must be one row per {.field year} and {.field area_code}.",
    "x" = "Found {extra} duplicate key{?s} in {nrow(keys)} row{?s}.",
    "i" = "An item or element dimension left in the table multiplies every
           per-capita figure it joins to."
  ))
}

# One inversion, two bounds. The ceiling's z is qnorm(share), NOT
# qnorm(1 - share): the share is of the population ABOVE the limit, so a larger
# tolerated share admits a higher supply.
.nb_compose <- function(terms, shortfall, ceiling, requirement_sd) {
  dplyr::transmute(
    terms,
    year = .data$year,
    area_code = .data$area_code,
    requirement_g_cap_day = .data$requirement_g_cap_day,
    safe_g_cap_day = .data$safe_g_cap_day,
    sigma_intake = .data$sigma,
    sigma_deficit = .nf_deficit_sd(.data$sigma, requirement_sd),
    omega = .data$omega,
    floor_g_cap_day = .nb_bound(
      .data$requirement_g_cap_day,
      stats::qnorm(1 - shortfall),
      .data$sigma,
      .data$sigma_deficit,
      .data$omega
    ),
    ceiling_g_cap_day = .nb_bound(
      ceiling$multiple * .data$safe_g_cap_day,
      stats::qnorm(ceiling$share),
      .data$sigma,
      .data$sigma_deficit,
      .data$omega
    )
  )
}

.nb_bound <- function(anchor, z, sigma_intake, sigma_deficit, omega) {
  anchor * exp(z * sigma_deficit + sigma_intake^2 / 2) / (1 - omega)
}

# Divide BOTH bounds by the diet's protein quality. This is the diet-side
# correction TRS 935 s14.1.5 prefers, written the other way round: comparing
# supply x q against a crude bound is the same inequality as comparing crude
# supply against bound / q, so the published supply series never moves while
# floor and ceiling move together. Correcting only the floor would leave the
# ceiling on crude protein.
.nb_apply_quality <- function(band, quality) {
  if (is.null(quality)) {
    return(dplyr::mutate(band, quality = 1, method_quality = "none"))
  }
  .check_columns(quality, c("year", "area_code", "quality"), "data$quality")
  .nb_check_unique(quality, "data$quality")
  stamp <- if (rlang::has_name(quality, "method_quality")) {
    dplyr::select(quality, "year", "area_code", "quality", "method_quality")
  } else {
    dplyr::mutate(
      dplyr::select(quality, "year", "area_code", "quality"),
      method_quality = "supplied"
    )
  }
  band |>
    dplyr::left_join(stamp, by = c("year", "area_code")) |>
    dplyr::mutate(
      floor_g_cap_day = .data$floor_g_cap_day / .data$quality,
      ceiling_g_cap_day = .data$ceiling_g_cap_day / .data$quality,
      method_quality = dplyr::coalesce(.data$method_quality, "none")
    )
}

# The prevalences the bounds invert, and the headcounts they imply. Kept
# optional because they need a supply the band itself does not: the band is a
# pair of thresholds, not a measurement.
.nb_add_prevalence <- function(band, data, ceiling) {
  supply <- data$supply
  if (is.null(supply)) {
    return(band)
  }
  .check_columns(
    supply,
    c("year", "area_code", "protein_g_cap_day"),
    "data$supply"
  )
  .nb_check_unique(supply, "data$supply")
  band |>
    dplyr::left_join(
      dplyr::select(supply, "year", "area_code", "protein_g_cap_day"),
      by = c("year", "area_code")
    ) |>
    dplyr::left_join(
      .nb_population(data),
      by = c("year", "area_code")
    ) |>
    dplyr::mutate(
      # Quality multiplies the supply here for the same reason it divides the
      # bounds above: one inequality, written from the other side. Leaving it
      # out would break the round trip -- prevalence at supply = floor would no
      # longer return `shortfall`.
      intake_log = log(
        .data$protein_g_cap_day * .data$quality * (1 - .data$omega)
      ) -
        .data$sigma_intake^2 / 2,
      prevalence_protein_deficit = .nf_prevalence(
        .data$intake_log - log(.data$requirement_g_cap_day),
        .data$sigma_deficit
      ),
      prevalence_protein_excess = stats::pnorm(
        (.data$intake_log -
          log(ceiling$multiple * .data$safe_g_cap_day)) /
          .data$sigma_deficit
      ),
      people_under = .data$prevalence_protein_deficit * .data$population,
      people_over = .data$prevalence_protein_excess * .data$population
    ) |>
    dplyr::select(-"protein_g_cap_day", -"intake_log", -"population")
}

# Population rides in on whichever input carries it: build_food_supply() and
# build_protein_requirement() both emit one, and they agree by construction
# because both divide by read_population(). Absent from both, the headcounts are
# NA rather than a guess.
.nb_population <- function(data) {
  for (table in list(data$supply, data$requirement)) {
    if (rlang::has_name(table, "population")) {
      return(dplyr::select(table, "year", "area_code", "population"))
    }
  }
  tibble::tibble(
    year = integer(0),
    area_code = integer(0),
    population = numeric(0)
  )
}

# The safe level already carries a 97.5th-percentile individual margin. Using it
# as the FLOOR's anchor, where the formula adds its own population margin,
# counts it twice -- the construction TRS 935 p.41 and p.241 forbid outright.
# It is the correct anchor for the CEILING, which is why that arrives on its own
# input rather than being confused with this one.
.nf_warn_safe_anchor <- function(requirement) {
  if (!rlang::has_name(requirement, "method_requirement")) {
    return(invisible())
  }
  if (!any(requirement$method_requirement == "safe", na.rm = TRUE)) {
    return(invisible())
  }
  cli::cli_warn(c(
    "!" = "{.field data$requirement} is stamped {.val safe}, which already
           carries an individual 97.5th-percentile margin.",
    "i" = "The floor adds its own population margin over {.arg requirement_sd},
           so the margin is counted twice.",
    "i" = "Pass the {.val average} requirement here and the {.val safe} one as
           {.field data$requirement_safe}."
  ))
}
