#' Primary items production
#'
#' @description
#' Get amount of crops, livestock and livestock products.
#'
#' @param file_path The local path where the input CSV is located. It is
#'   recommended to use an autogenerated path by `get_file_path()` function.
#'
#' @returns
#' A tibble with the item production data.
#' It contains the following columns:
#' - `year`: The year in which the recorded event occurred.
#' - `area_code`: FAOSTAT internal code for each country from where the data
#'    is from. Equivalences with ISO 3166-1 numeric can be found in the
#'    _Area Codes_ CSV from the zip file that can be downloaded from
#'    [FAOSTAT](https://www.fao.org/faostat/en/#data/FBS). TODO: Think about
#'    this, would be nice to use ISO3 codes but won't be enough for our periods
#' - `item_prod_code`: FAOSTAT internal code for each produced item.
#' - `item_cbs_code`: FAOSTAT internal code for each commodity balance sheet
#'    item. The commodity balance sheet contains an aggregated version of
#'    production items. This field is the code for the corresponding
#'    aggregated item.
#' - `live_anim_code`: Commodity balance sheet code for the type of livestock
#'    that produces the livestock product. It can be:
#'    - `NA`: The entry is not a livestock product.
#'    - Non-`NA`: The code for the livestock type. The name can also be
#'    retrieved by using `add_item_cbs_name()`.
#' - `unit`: Measurement unit for the data. Here, keep in mind three groups of
#'    items: crops (e.g. `Apples and products`, `Beans`...), livestock (e.g.
#'    `Cattle, dairy`, `Goats`...) and livestock products (e.g. `Poultry
#'    Meat`, `Offals, Edible`...). Then the unit can be one of:
#'    - `tonnes`: Available for crops and livestock products.
#'    - `ha`: Hectares, available for crops.
#'    - `t_ha`: Tonnes per hectare, available for crops.
#'    - `heads`: Number of animals, available for livestock.
#'    - `LU`: Standard Livestock Unit measure, available for livestock.
#'    - `t_head`: tonnes per head, available for livestock products.
#'    - `t_LU`: tonnes per Livestock Unit, available for livestock products.
#' - `value`: The amount of item produced, measured in `unit`.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' get_primary_production(get_file_path("primary_prod"))
#' }
get_primary_production <- function(file_path) {
  file_path |>
    readr::read_csv() |>
    dplyr::rename_with(tolower) |>
    dplyr::select(
      year,
      area_code,
      item_prod_code = item_code,
      item_cbs_code = item_code_cbs,
      live_anim_code,
      unit,
      value
    )
}

#' Crop residue items
#'
#' @description
#' Get type and amount of residue produced for each crop production item.
#'
#' @param file_path The local path where the input CSV is located. It is
#'   recommended to use an autogenerated path by `get_file_path()` function.
#'
#' @returns
#' A tibble with the crop residue data.
#' It contains the following columns:
#' - `year`: The year in which the recorded event occurred.
#' - `area_code`: FAOSTAT internal code for each country from where the data
#'    is from. Equivalences with ISO 3166-1 numeric can be found in the
#'    _Area Codes_ CSV from the zip file that can be downloaded from
#'    [FAOSTAT](https://www.fao.org/faostat/en/#data/FBS). TODO: Think about
#'    this, would be nice to use ISO3 codes but won't be enough for our periods
#' - `item_prod_code`: FAOSTAT internal code for each production item. This is
#'    the crop that is generating the residue.
#' - `item_cbs_code`: FAOSTAT internal code for each commodity balance sheet
#'    item. This is the obtained residue. In the commodity balance sheet,
#'    this can be three different items right now:
#'    - `2105`: `Straw`
#'    - `2106`: `Other crop residues`
#'    - `2107`: `Firewood`
#'
#'    These are actually not FAOSTAT defined items, but custom defined by us.
#'    When necessary, FAOSTAT codes are extended for our needs.
#' - `value`: The amount of residue produced, measured in tonnes.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' get_primary_residues(get_file_path("crop_residues"))
#' }
get_primary_residues <- function(file_path) {
  file_path |>
    readr::read_csv() |>
    dplyr::rename_with(tolower) |>
    dplyr::filter(product_residue == "Residue") |>
    add_area_code(name_column = "area") |>
    add_item_cbs_code(name_column = "item_cbs") |>
    add_item_prod_code(name_column = "item_prod") |>
    dplyr::select(
      year,
      area_code,
      item_prod_code = item_prod_code,
      item_cbs_code,
      value = prod_ygpit_mg
    )
}
