# TODO: Revisit the whole file. I'm pretty sure there are mistakes,
# along with incomplete parts. It's better to first finish the model
# and then come back here.

#' Supply and use tables
#'
#' @description
#' Create a table with processes, their inputs (_use_) and their
#' outputs (_supply_).
#'
#' @param example If `TRUE`, return a small example output without downloading
#'   remote data. Default is `FALSE`.
#'
#' @returns
#' A tibble with the supply and use data for processes.
#' It contains the following columns:
#' - `year`: The year in which the recorded event occurred.
#' - `area_code`: The code of the country where the data is from. For code
#'    details see e.g. `add_area_name()`.
#' - `proc_group`: The type of process taking place. It can be one of:
#'    - `crop_production`: Production of crops and their residues, e.g. rice
#'    production, coconut production, etc.
#'    - `husbandry`: Animal husbandry, e.g. dairy cattle husbandry, non-dairy
#'    cattle husbandry, layers chickens farming, etc.
#'    - `animal_draught`: Annual useful work energy generated by draft
#'    animals.
#'    - `slaughtering`: Slaughter of live animals into meat, edible offals,
#'    raw animal fats, and hides/skins.
#'    - `processing`: Derived subproducts obtained from processing other items.
#'    The items used as inputs are those that have a non-zero processing use in
#'    the commodity balance sheet. See `get_wide_cbs()` for more details.
#'    In each process there is a single input. In some processes like olive oil
#'    extraction or soyabean oil extraction this might make sense. Others like
#'    alcohol production need multiple inputs (e.g. multiple crops work), so
#'    in this data there would not be a process like alcohol production but
#'    rather a _virtual_ process like 'Wheat and products processing', giving
#'    all its possible outputs. This is a constraint because of how the data was
#'    obtained and might be improved in the future. See
#'    `get_processing_coefs()` for more details.
#' - `proc_cbs_code`: The code of the main item in the process taking place.
#'    Together with `proc_group`, these two columns uniquely represent a
#'    process. The main item is predictable depending on the value of
#'    `proc_group`:
#'    - `crop_production`: The code is from the item for which seed usage
#'    (if any) is reported in the commodity balance sheet (see
#'    `get_wide_cbs()` for more). For example, the rice code for a rice
#'    production process or the cottonseed code for the cotton production one.
#'    - `husbandry`: The code of the farmed animal, e.g. bees for beekeeping,
#'    non-dairy cattle for non-dairy cattle husbandry, etc.
#'    - `slaughtering`: The code of the live animal being slaughtered, e.g.
#'    non-dairy cattle for cattle slaughter.
#'    - `processing`: The code of the item that is used as input, i.e., the one
#'    that is processed to get other derived products. This uniquely defines a
#'    process within the group because of the nature of the data that was used,
#'    which you can see in `get_processing_coefs()`.
#'
#'    For code details see e.g. `add_item_cbs_name()`.
#' - `item_cbs_code`: The code of the item produced or used in the process.
#'    Note that this might be the same value as `proc_cbs_code`, e.g., in rice
#'    production process for the row defining the amount of rice produced or
#'    the amount of rice seed as input, but it might also have a different
#'    value, e.g. for the row defining the amount of straw residue from rice
#'    production. For code details see e.g. `add_item_cbs_name()`.
#' - `type`: Can have two values:
#'    - `use`: The given item is an input of the process.
#'    - `supply`: The given item is an output of the process.
#' - `value`: Quantity in the item's own unit. Most items are measured in
#'   tonnes; live animals are measured in heads; animal draught is measured as
#'   annual useful work energy (TJ).
#'
#' @export
#'
#' @examples
#' build_supply_use(example = TRUE)
build_supply_use <- function(example = FALSE) {
  if (example) {
    return(.example_build_supply_use())
  }

  .build_supply_use_from_inputs(
    items_prod = whep::items_prod,
    items_cbs = whep::items_cbs,
    coeffs = get_processing_coefs(),
    cbs = get_wide_cbs(),
    crop_residues = get_primary_residues(),
    primary_prod = get_primary_production(),
    feed_intake = get_feed_intake()
  ) |>
    .add_reporting_polity_columns()
}

.build_supply_use_from_inputs <- function(
  items_prod,
  items_cbs,
  coeffs,
  cbs,
  crop_residues,
  primary_prod,
  feed_intake
) {
  husbandry_items <- items_cbs |>
    dplyr::filter(
      item_type %in% c("livestock", "livestock_meat", "livestock_draft")
    ) |>
    dplyr::select(live_anim_code = item_cbs_code)

  draft_items <- items_cbs |>
    dplyr::filter(item_type == "livestock_draft") |>
    dplyr::select(live_anim_code = item_cbs_code)

  animal_draught_item_code <- .animal_draught_item_code(items_cbs)

  slaughter_product_items <- items_cbs |>
    dplyr::filter(item_type == "slaughter_product") |>
    dplyr::select(item_cbs_code)

  slaughter_items <- .slaughter_livestock_items(
    primary_prod,
    slaughter_product_items$item_cbs_code
  )

  crop_prod_items <- items_prod |>
    dplyr::filter(item_type == "crop_product") |>
    dplyr::select(item_prod_code)

  dplyr::bind_rows(
    .build_crop_production(
      crop_prod_items,
      cbs,
      primary_prod,
      crop_residues,
      draft_items,
      animal_draught_item_code
    ),
    .build_animal_draught(
      primary_prod,
      draft_items,
      animal_draught_item_code
    ),
    .build_husbandry(
      husbandry_items,
      feed_intake,
      primary_prod,
      cbs,
      slaughter_product_items
    ),
    .build_slaughtering(
      slaughter_items,
      slaughter_product_items,
      cbs,
      primary_prod
    ),
    .build_processing(coeffs),
  ) |>
    dplyr::select(
      year,
      area_code,
      proc_group,
      proc_cbs_code,
      item_cbs_code,
      type,
      value
    )
}

.build_crop_production <- function(
  crop_prod_items,
  cbs,
  primary_prod,
  crop_residues,
  draft_items = tibble::tibble(live_anim_code = integer()),
  animal_draught_item_code = integer()
) {
  supply_crop_production <- .build_supply_crop_production(
    crop_prod_items,
    primary_prod,
    crop_residues
  ) |>
    dplyr::mutate(type = "supply")

  cbs_items <- supply_crop_production |>
    dplyr::distinct(item_cbs_code)

  use_crop_production <- dplyr::bind_rows(
    .build_use_crop_production(cbs_items, cbs),
    .build_use_crop_draught(
      crop_prod_items,
      primary_prod,
      draft_items,
      animal_draught_item_code
    )
  ) |>
    dplyr::mutate(type = "use")

  dplyr::bind_rows(supply_crop_production, use_crop_production) |>
    dplyr::mutate(proc_group = "crop_production")
}

.build_supply_crop_production <- function(
  crop_prod_items,
  primary_prod,
  crop_residues
) {
  supply_crop_product <- .build_supply_crop_product(
    crop_prod_items,
    primary_prod
  )

  cbs_items <- supply_crop_product |>
    dplyr::distinct(item_cbs_code_crop = item_cbs_code)

  supply_crop_residue <- .build_supply_crop_residue(cbs_items, crop_residues)

  dplyr::bind_rows(supply_crop_product, supply_crop_residue)
}

.build_use_crop_production <- function(cbs_items, cbs) {
  cbs |>
    dplyr::inner_join(cbs_items, "item_cbs_code") |>
    dplyr::filter(seed > 0) |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = item_cbs_code,
      item_cbs_code = item_cbs_code,
      value = seed
    )
}

.build_supply_crop_product <- function(crop_prod_items, primary_prod) {
  primary_prod |>
    dplyr::filter(unit == "tonnes") |>
    dplyr::inner_join(crop_prod_items, "item_prod_code") |>
    dplyr::summarise(
      value = sum(value),
      .by = c(year, area_code, item_cbs_code)
    ) |>
    dplyr::mutate(proc_cbs_code = item_cbs_code)
}

.build_supply_crop_residue <- function(cbs_items, crop_residues) {
  crop_residues |>
    dplyr::inner_join(cbs_items, "item_cbs_code_crop") |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = item_cbs_code_crop,
      item_cbs_code = item_cbs_code_residue,
      value
    )
}

.build_use_crop_draught <- function(
  crop_prod_items,
  primary_prod,
  draft_items = tibble::tibble(live_anim_code = integer()),
  animal_draught_item_code = integer()
) {
  if (
    length(animal_draught_item_code) == 0L ||
      nrow(draft_items) == 0L
  ) {
    return(.empty_supply_use_rows())
  }

  draught_supply <- .build_animal_draught_supply(
    primary_prod,
    draft_items,
    animal_draught_item_code
  ) |>
    dplyr::summarise(
      value = sum(value, na.rm = TRUE),
      .by = c(year, area_code)
    )
  if (nrow(draught_supply) == 0L) {
    return(.empty_supply_use_rows())
  }

  crop_area <- primary_prod |>
    dplyr::filter(unit == "ha") |>
    dplyr::inner_join(crop_prod_items, "item_prod_code") |>
    dplyr::summarise(
      crop_area = sum(value, na.rm = TRUE),
      .by = c(year, area_code, item_cbs_code)
    ) |>
    dplyr::filter(.data$crop_area > 0)
  if (nrow(crop_area) == 0L) {
    return(.empty_supply_use_rows())
  }

  area_totals <- crop_area |>
    dplyr::summarise(
      total_crop_area = sum(.data$crop_area, na.rm = TRUE),
      .by = c(year, area_code)
    ) |>
    dplyr::filter(.data$total_crop_area > 0)

  crop_area |>
    dplyr::inner_join(area_totals, by = c("year", "area_code")) |>
    dplyr::inner_join(draught_supply, by = c("year", "area_code")) |>
    dplyr::transmute(
      year,
      area_code,
      proc_cbs_code = item_cbs_code,
      item_cbs_code = animal_draught_item_code,
      value = .data$value * .data$crop_area / .data$total_crop_area
    )
}

.build_husbandry <- function(
  husbandry_items,
  feed_intake,
  primary_prod,
  cbs = NULL,
  slaughter_product_items = tibble::tibble(item_cbs_code = integer())
) {
  dplyr::bind_rows(
    .build_use_husbandry(feed_intake),
    .build_supply_husbandry(
      husbandry_items,
      primary_prod,
      cbs,
      slaughter_product_items
    ),
  ) |>
    dplyr::mutate(proc_group = "husbandry")
}

.build_use_husbandry <- function(feed_intake) {
  feed_intake |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = live_anim_code,
      item_cbs_code,
      value = supply
    ) |>
    dplyr::mutate(type = "use")
}

.build_supply_husbandry <- function(
  husbandry_items,
  primary_prod,
  cbs = NULL,
  slaughter_product_items = tibble::tibble(item_cbs_code = integer())
) {
  dplyr::bind_rows(
    .build_livestock_supply(
      primary_prod,
      husbandry_items,
      cbs
    ),
    .build_livestock_prods_supply(
      primary_prod,
      husbandry_items,
      slaughter_product_items
    ),
  ) |>
    dplyr::mutate(type = "supply")
}

.build_livestock_supply <- function(
  primary_prod,
  husbandry_items,
  cbs = NULL
) {
  required_cbs <- c("year", "area_code", "item_cbs_code", "production")
  if (!is.null(cbs) && all(required_cbs %in% names(cbs))) {
    return(
      cbs |>
        dplyr::inner_join(
          husbandry_items,
          dplyr::join_by(item_cbs_code == live_anim_code)
        ) |>
        dplyr::transmute(
          year,
          area_code,
          proc_cbs_code = item_cbs_code,
          item_cbs_code,
          value = production
        )
    )
  }

  primary_prod |>
    dplyr::filter(unit == "heads") |>
    dplyr::inner_join(
      husbandry_items,
      dplyr::join_by(item_cbs_code == live_anim_code)
    ) |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = item_cbs_code,
      item_cbs_code = item_cbs_code,
      value
    )
}

.build_animal_draught_supply <- function(
  primary_prod,
  draft_items = tibble::tibble(live_anim_code = integer()),
  animal_draught_item_code = integer()
) {
  if (
    length(animal_draught_item_code) == 0L ||
      nrow(draft_items) == 0L
  ) {
    return(.empty_supply_use_rows())
  }

  draft_items <- .add_animal_draught_work_hours(draft_items)

  primary_prod |>
    dplyr::filter(unit == "LU") |>
    dplyr::inner_join(
      draft_items,
      dplyr::join_by(item_cbs_code == live_anim_code)
    ) |>
    dplyr::filter(.data$work_hours_day > 0) |>
    dplyr::mutate(
      proc_cbs_code = .data$item_cbs_code,
      value = .data$value *
        .data$work_hours_day *
        .animal_draught_tj_per_lu_hour() *
        365,
      item_cbs_code = as.integer(animal_draught_item_code)
    ) |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code,
      item_cbs_code,
      value
    )
}

.build_animal_draught <- function(
  primary_prod,
  draft_items = tibble::tibble(live_anim_code = integer()),
  animal_draught_item_code = integer()
) {
  .build_animal_draught_supply(
    primary_prod,
    draft_items,
    animal_draught_item_code
  ) |>
    dplyr::mutate(
      type = "supply",
      proc_group = "animal_draught"
    )
}

.build_livestock_prods_supply <- function(
  primary_prod,
  husbandry_items,
  exclude_product_items = tibble::tibble(item_cbs_code = integer())
) {
  excluded_items <- exclude_product_items$item_cbs_code %||% integer()

  primary_prod |>
    dplyr::filter(
      unit == "tonnes",
      !item_cbs_code %in% excluded_items
    ) |>
    dplyr::inner_join(husbandry_items, "live_anim_code") |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = live_anim_code,
      item_cbs_code,
      value
    )
}

.build_slaughtering <- function(
  slaughter_items,
  slaughter_product_items,
  cbs,
  primary_prod
) {
  required_cbs <- c(
    "year",
    "area_code",
    "item_cbs_code",
    "processing"
  )
  if (
    nrow(slaughter_items) == 0L ||
      nrow(slaughter_product_items) == 0L ||
      is.null(cbs) ||
      !all(required_cbs %in% names(cbs))
  ) {
    return(.empty_supply_use_rows())
  }

  slaughter_supply <- primary_prod |>
    dplyr::filter(
      unit == "tonnes",
      !is.na(live_anim_code)
    ) |>
    dplyr::inner_join(slaughter_items, "live_anim_code") |>
    dplyr::inner_join(slaughter_product_items, "item_cbs_code") |>
    dplyr::summarise(
      value = sum(value, na.rm = TRUE),
      .by = c(year, area_code, live_anim_code, item_cbs_code)
    ) |>
    dplyr::transmute(
      year,
      area_code,
      proc_cbs_code = live_anim_code,
      item_cbs_code,
      value,
      type = "supply"
    )

  slaughter_keys <- slaughter_supply |>
    dplyr::distinct(year, area_code, live_anim_code = proc_cbs_code)

  cbs_slaughter <- cbs |>
    dplyr::inner_join(
      slaughter_items,
      dplyr::join_by(item_cbs_code == live_anim_code)
    )

  slaughter_use <- slaughter_keys |>
    dplyr::inner_join(
      cbs_slaughter,
      by = c(
        "year",
        "area_code",
        "live_anim_code" = "item_cbs_code"
      )
    ) |>
    dplyr::transmute(
      year,
      area_code,
      proc_cbs_code = live_anim_code,
      item_cbs_code = live_anim_code,
      value = processing
    ) |>
    dplyr::filter(.data$value > 0) |>
    dplyr::mutate(type = "use")

  dplyr::bind_rows(slaughter_use, slaughter_supply) |>
    dplyr::mutate(proc_group = "slaughtering")
}

.build_processing <- function(coeffs) {
  processing_use <- coeffs |>
    dplyr::distinct(
      year,
      area_code,
      proc_cbs_code = item_cbs_code_to_process,
      item_cbs_code = item_cbs_code_to_process,
      value = value_to_process
    ) |>
    dplyr::mutate(type = "use")

  processing_supply <- coeffs |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = item_cbs_code_to_process,
      item_cbs_code = item_cbs_code_processed,
      value = final_value_processed
    ) |>
    dplyr::mutate(type = "supply")

  dplyr::bind_rows(processing_use, processing_supply) |>
    dplyr::mutate(proc_group = "processing")
}

.animal_draught_item_code <- function(items_cbs) {
  item <- items_cbs |>
    dplyr::filter(.data$item_cbs_code == 4000L) |>
    dplyr::pull(.data$item_cbs_code) |>
    unique()
  if (length(item) == 0L) {
    return(integer())
  }
  as.integer(item[[1L]])
}

.add_animal_draught_work_hours <- function(draft_items) {
  if (!"work_hours_day" %in% names(draft_items)) {
    draft_items$work_hours_day <- NA_real_
  }

  draft_items |>
    dplyr::left_join(
      .animal_draught_work_hours(),
      by = "live_anim_code",
      suffix = c("", "_default")
    ) |>
    dplyr::mutate(
      work_hours_day = dplyr::coalesce(
        .data$work_hours_day,
        .data$work_hours_day_default
      )
    ) |>
    dplyr::select(-dplyr::any_of("work_hours_day_default"))
}

.animal_draught_work_hours <- function() {
  tibble::tibble(
    live_anim_code = c(946L, 1096L, 1107L, 1110L, 1126L, 1157L),
    category = c(
      "Buffalo",
      "Horses",
      "Mules and Asses",
      "Mules and Asses",
      "Camels",
      "Camels"
    )
  ) |>
    dplyr::left_join(
      whep::livestock_production_defaults |>
        dplyr::select(category, work_hours_day),
      by = "category"
    ) |>
    dplyr::select(-"category")
}

.animal_draught_tj_per_lu_hour <- function() {
  # Useful work energy from 0.5 kW sustained draught power per livestock unit.
  0.5 * 3.6 / 1e6
}

.empty_supply_use_rows <- function() {
  tibble::tibble(
    year = integer(),
    area_code = integer(),
    proc_cbs_code = integer(),
    item_cbs_code = integer(),
    value = numeric()
  )
}
