# TODO: Revisit the whole file. I'm pretty sure there are mistakes,
# along with incomplete parts. It's better to first finish the model
# and then come back here.

#' Supply and use tables
#'
#' @description
#' Create a table with processes, their inputs (_use_) and their
#' outputs (_supply_).
#'
#' @param example If `TRUE`, return a small example output without downloading
#'   remote data. Default is `FALSE`.
#'
#' @returns
#' A tibble with the supply and use data for processes.
#' It contains the following columns:
#' - `year`: The year in which the recorded event occurred.
#' - `area_code`: The code of the country where the data is from. For code
#'    details see e.g. `add_area_name()`.
#' - `proc_group`: The type of process taking place. It can be one of:
#'    - `crop_production`: Production of crops and their residues, e.g. rice
#'    production, coconut production, etc.
#'    - `husbandry`: Animal husbandry, e.g. dairy cattle husbandry, non-dairy
#'    cattle husbandry, layers chickens farming, etc.
#'    - `animal_draught`: Annual useful work energy generated by draft
#'    animals.
#'    - `slaughtering`: Slaughter of live animals into meat, edible offals,
#'    raw animal fats, and hides/skins.
#'    - `processing`: Derived subproducts obtained from processing other items.
#'    The items used as inputs are those that have a non-zero processing use in
#'    the commodity balance sheet. See `get_wide_cbs()` for more details.
#'    In each process there is a single input. In some processes like olive oil
#'    extraction or soyabean oil extraction this might make sense. Others like
#'    alcohol production need multiple inputs (e.g. multiple crops work), so
#'    in this data there would not be a process like alcohol production but
#'    rather a _virtual_ process like 'Wheat and products processing', giving
#'    all its possible outputs. This is a constraint because of how the data was
#'    obtained and might be improved in the future. See
#'    `get_processing_coefs()` for more details.
#' - `proc_cbs_code`: The code of the main item in the process taking place.
#'    Together with `proc_group`, these two columns uniquely represent a
#'    process. The main item is predictable depending on the value of
#'    `proc_group`:
#'    - `crop_production`: The code is from the item for which seed usage
#'    (if any) is reported in the commodity balance sheet, except for field
#'    co-products where the process uses the field aggregate item. For example,
#'    rice production uses the rice code, while seed cotton production uses the
#'    seed cotton code and supplies both cottonseed and cotton lint.
#'    - `husbandry`: The code of the farmed animal, e.g. bees for beekeeping,
#'    non-dairy cattle for non-dairy cattle husbandry, etc.
#'    - `slaughtering`: The code of the live animal being slaughtered, e.g.
#'    non-dairy cattle for cattle slaughter.
#'    - `processing`: The code of the item that is used as input, i.e., the one
#'    that is processed to get other derived products. This uniquely defines a
#'    process within the group because of the nature of the data that was used,
#'    which you can see in `get_processing_coefs()`.
#'
#'    For code details see e.g. `add_item_cbs_name()`.
#' - `item_cbs_code`: The code of the item produced or used in the process.
#'    Note that this might be the same value as `proc_cbs_code`, e.g., in rice
#'    production process for the row defining the amount of rice produced or
#'    the amount of rice seed as input, but it might also have a different
#'    value, e.g. for the row defining the amount of straw residue from rice
#'    production. For code details see e.g. `add_item_cbs_name()`.
#' - `type`: Can have two values:
#'    - `use`: The given item is an input of the process.
#'    - `supply`: The given item is an output of the process.
#' - `value`: Quantity in the item's own unit. Most items are measured in
#'   tonnes; live animals are measured in heads; animal draught is measured as
#'   annual useful work energy (TJ).
#'
#' @export
#'
#' @examples
#' build_supply_use(example = TRUE)
build_supply_use <- function(example = FALSE) {
  if (example) {
    return(.example_build_supply_use())
  }

  cbs <- get_wide_cbs()
  # Production and residues are per-country; supply-use joins the
  # FABIO-grain CBS by area, so collapse them at this boundary.
  primary_prod <- get_primary_production() |>
    dplyr::select(-dplyr::any_of(c("source", "fao_flag"))) |>
    collapse_to_fabio_regions()

  .build_supply_use_from_inputs(
    items_prod = whep::items_prod,
    items_cbs = whep::items_cbs,
    coeffs = get_processing_coefs(),
    cbs = cbs,
    crop_residues = collapse_to_fabio_regions(get_primary_residues()),
    primary_prod = primary_prod,
    feed_intake = .build_redistribute_intake(
      grain = "national",
      demand_tier = "ipcc",
      production = primary_prod,
      cbs = cbs
    )
  ) |>
    .add_reporting_polity_columns()
}

.build_supply_use_from_inputs <- function(
  items_prod,
  items_cbs,
  coeffs,
  cbs,
  crop_residues,
  primary_prod,
  feed_intake
) {
  husbandry_items <- items_cbs |>
    dplyr::filter(
      item_type %in% c("livestock", "livestock_meat", "livestock_draft")
    ) |>
    dplyr::select(live_anim_code = item_cbs_code)

  draft_items <- items_cbs |>
    dplyr::filter(item_type == "livestock_draft") |>
    dplyr::select(live_anim_code = item_cbs_code)

  animal_draught_item_code <- .animal_draught_item_code(items_cbs)

  slaughter_product_items <- items_cbs |>
    dplyr::filter(item_type == "slaughter_product") |>
    dplyr::select(item_cbs_code)

  slaughter_items <- .slaughter_livestock_items(
    primary_prod,
    slaughter_product_items$item_cbs_code
  )

  crop_prod_items <- items_prod |>
    dplyr::filter(item_type == "crop_product") |>
    dplyr::select(item_prod_code)

  dplyr::bind_rows(
    .build_crop_production(
      crop_prod_items,
      cbs,
      primary_prod,
      crop_residues,
      draft_items,
      animal_draught_item_code
    ),
    .build_animal_draught(
      primary_prod,
      draft_items,
      animal_draught_item_code
    ),
    .build_husbandry(
      husbandry_items,
      feed_intake,
      primary_prod,
      cbs,
      slaughter_product_items
    ),
    .build_slaughtering(
      slaughter_items,
      slaughter_product_items,
      cbs,
      primary_prod
    ),
    .build_processing(coeffs),
  ) |>
    dplyr::select(
      year,
      area_code,
      proc_group,
      proc_cbs_code,
      item_cbs_code,
      type,
      value
    )
}

.build_crop_production <- function(
  crop_prod_items,
  cbs,
  primary_prod,
  crop_residues,
  draft_items = tibble::tibble(live_anim_code = integer()),
  animal_draught_item_code = integer()
) {
  supply_crop_production <- .build_supply_crop_production(
    crop_prod_items,
    primary_prod,
    crop_residues
  ) |>
    dplyr::mutate(type = "supply")

  cbs_items <- supply_crop_production |>
    dplyr::summarise(
      supply_value = sum(.data$value, na.rm = TRUE),
      .by = c(year, area_code, proc_cbs_code, item_cbs_code)
    )

  use_crop_production <- dplyr::bind_rows(
    .build_use_crop_production(cbs_items, cbs),
    .build_use_crop_draught(
      crop_prod_items,
      primary_prod,
      draft_items,
      animal_draught_item_code
    )
  ) |>
    dplyr::mutate(type = "use")

  dplyr::bind_rows(supply_crop_production, use_crop_production) |>
    dplyr::mutate(proc_group = "crop_production")
}

.build_supply_crop_production <- function(
  crop_prod_items,
  primary_prod,
  crop_residues
) {
  supply_crop_product <- .build_supply_crop_product(
    crop_prod_items,
    primary_prod
  )

  cbs_items <- supply_crop_product |>
    dplyr::distinct(proc_cbs_code)

  supply_crop_residue <- .build_supply_crop_residue(cbs_items, crop_residues)

  dplyr::bind_rows(supply_crop_product, supply_crop_residue)
}

.build_use_crop_production <- function(cbs_items, cbs) {
  cbs_items <- .ensure_process_column(cbs_items, "item_cbs_code")

  by <- "item_cbs_code"
  if (all(c("year", "area_code") %in% names(cbs_items))) {
    by <- c("year", "area_code", "item_cbs_code")
  }

  use <- cbs |>
    dplyr::inner_join(
      cbs_items,
      by = by,
      relationship = "many-to-many"
    ) |>
    dplyr::filter(seed > 0)

  if ("supply_value" %in% names(use)) {
    use <- use |>
      dplyr::mutate(
        supply_value = tidyr::replace_na(.data$supply_value, 0),
        total_supply_value = sum(.data$supply_value, na.rm = TRUE),
        process_count = dplyr::n(),
        seed_share = dplyr::if_else(
          .data$total_supply_value > 0,
          .data$supply_value / .data$total_supply_value,
          1 / .data$process_count
        ),
        value = .data$seed * .data$seed_share,
        .by = c(year, area_code, item_cbs_code)
      )
  } else {
    use <- use |>
      dplyr::mutate(value = .data$seed)
  }

  use |>
    dplyr::summarise(
      value = sum(.data$value, na.rm = TRUE),
      .by = c(year, area_code, proc_cbs_code, item_cbs_code)
    ) |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code,
      item_cbs_code,
      value
    )
}

.build_supply_crop_product <- function(crop_prod_items, primary_prod) {
  double_process_map <- .double_crop_process_map()

  primary_prod |>
    dplyr::filter(unit == "tonnes") |>
    dplyr::inner_join(crop_prod_items, "item_prod_code") |>
    dplyr::left_join(
      double_process_map,
      by = c("item_prod_code", "item_cbs_code")
    ) |>
    dplyr::mutate(
      proc_cbs_code = dplyr::coalesce(
        .data$proc_cbs_code,
        .data$item_cbs_code
      )
    ) |>
    dplyr::summarise(
      value = sum(value),
      .by = c(year, area_code, proc_cbs_code, item_cbs_code)
    )
}

.double_crop_process_map <- function() {
  double_products <- .primary_double_product_map()
  if (nrow(double_products) == 0L) {
    return(tibble::tibble(
      item_prod_code = integer(),
      item_cbs_code = integer(),
      proc_cbs_code = integer()
    ))
  }

  processes <- .primary_double_area_map() |>
    dplyr::select(family, output_key, proc_cbs_code = area_item_cbs_code)

  double_products |>
    dplyr::left_join(processes, by = c("family", "output_key")) |>
    dplyr::mutate(
      proc_cbs_code = dplyr::coalesce(
        .data$proc_cbs_code,
        .data$item_cbs_code
      )
    ) |>
    dplyr::select(
      item_prod_code,
      item_cbs_code,
      proc_cbs_code
    ) |>
    dplyr::distinct()
}

.double_crop_area_process_map <- function(crop_prod_items = NULL) {
  area_map <- .primary_double_area_map()
  if (nrow(area_map) == 0L) {
    return(tibble::tibble(
      item_prod_code = integer(),
      item_cbs_code = integer(),
      proc_cbs_code = integer()
    ))
  }

  if (!is.null(crop_prod_items)) {
    active_families <- .primary_double_product_map() |>
      dplyr::semi_join(crop_prod_items, by = "item_prod_code") |>
      dplyr::distinct(family, output_key)

    area_map <- area_map |>
      dplyr::semi_join(active_families, by = c("family", "output_key"))
  }

  area_map |>
    dplyr::transmute(
      item_prod_code = .data$area_item_prod_code,
      item_cbs_code = .data$area_item_cbs_code,
      proc_cbs_code = .data$area_item_cbs_code
    ) |>
    dplyr::distinct()
}

.primary_double_product_map <- function() {
  products <- .primary_double_item_map(c("Primary", "Multi"))

  products |>
    dplyr::mutate(
      output_key = paste(
        sort(unique(.data$item_cbs_code)),
        collapse = ":"
      ),
      .by = family
    ) |>
    dplyr::select(
      family,
      output_key,
      item_prod_code,
      item_cbs_code
    )
}

.primary_double_area_map <- function() {
  area_items <- .primary_double_item_map(c("Primary_area", "Multi_area"))
  if (nrow(area_items) == 0L) {
    return(tibble::tibble(
      family = character(),
      output_key = character(),
      area_item_prod_code = integer(),
      area_item_cbs_code = integer()
    ))
  }

  keys <- .primary_double_product_map() |>
    dplyr::distinct(family, output_key)

  area_items |>
    dplyr::left_join(keys, by = "family") |>
    dplyr::filter(!is.na(.data$output_key)) |>
    dplyr::transmute(
      family,
      output_key,
      area_item_prod_code = item_prod_code,
      area_item_cbs_code = item_cbs_code
    ) |>
    dplyr::distinct()
}

.primary_double_item_map <- function(multi_types = NULL) {
  item_map <- whep::items_prod_full |>
    dplyr::transmute(
      item_prod_code = .as_integer_quiet(.data$item_prod_code),
      item_cbs_code = .as_integer_quiet(.data$item_cbs_code)
    ) |>
    dplyr::filter(
      !is.na(.data$item_prod_code),
      !is.na(.data$item_cbs_code)
    ) |>
    dplyr::distinct()

  result <- whep::primary_double |>
    dplyr::transmute(
      family = dplyr::coalesce(.data$Item_area, .data$item_prod),
      item_prod_code = .as_integer_quiet(.data$item_prod_code),
      multi_type = .data$Multi_type
    )

  if (!is.null(multi_types)) {
    result <- result |>
      dplyr::filter(.data$multi_type %in% .env$multi_types)
  }

  result |>
    dplyr::left_join(item_map, by = "item_prod_code") |>
    dplyr::filter(!is.na(.data$item_cbs_code)) |>
    dplyr::select(family, item_prod_code, item_cbs_code, multi_type) |>
    dplyr::distinct()
}

.as_integer_quiet <- function(x) {
  suppressWarnings(as.integer(x))
}

.ensure_process_column <- function(data, item_column) {
  if ("proc_cbs_code" %in% names(data)) {
    return(data)
  }

  data |>
    dplyr::mutate(proc_cbs_code = .data[[item_column]])
}

.build_supply_crop_residue <- function(cbs_items, crop_residues) {
  cbs_items <- .ensure_process_column(cbs_items, "item_cbs_code_crop")
  processes <- cbs_items |>
    dplyr::distinct(proc_cbs_code)

  crop_residues |>
    dplyr::inner_join(
      processes,
      by = c("item_cbs_code_crop" = "proc_cbs_code"),
      relationship = "many-to-many"
    ) |>
    dplyr::mutate(proc_cbs_code = .data$item_cbs_code_crop) |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code,
      item_cbs_code = item_cbs_code_residue,
      value
    )
}

.build_use_crop_draught <- function(
  crop_prod_items,
  primary_prod,
  draft_items = tibble::tibble(live_anim_code = integer()),
  animal_draught_item_code = integer()
) {
  if (
    length(animal_draught_item_code) == 0L ||
      nrow(draft_items) == 0L
  ) {
    return(.empty_supply_use_rows())
  }

  draught_supply <- .build_animal_draught_supply(
    primary_prod,
    draft_items,
    animal_draught_item_code
  ) |>
    dplyr::summarise(
      value = sum(value, na.rm = TRUE),
      .by = c(year, area_code)
    )
  if (nrow(draught_supply) == 0L) {
    return(.empty_supply_use_rows())
  }

  crop_area <- .build_crop_area_processes(crop_prod_items, primary_prod)
  if (nrow(crop_area) == 0L) {
    return(.empty_supply_use_rows())
  }

  area_totals <- crop_area |>
    dplyr::summarise(
      total_crop_area = sum(.data$crop_area, na.rm = TRUE),
      .by = c(year, area_code)
    ) |>
    dplyr::filter(.data$total_crop_area > 0)
  if (nrow(area_totals) == 0L) {
    return(.empty_supply_use_rows())
  }

  crop_area |>
    dplyr::inner_join(area_totals, by = c("year", "area_code")) |>
    dplyr::inner_join(draught_supply, by = c("year", "area_code")) |>
    dplyr::transmute(
      year,
      area_code,
      proc_cbs_code,
      item_cbs_code = animal_draught_item_code,
      value = .data$value * .data$crop_area / .data$total_crop_area
    )
}

.build_crop_area_processes <- function(crop_prod_items, primary_prod) {
  double_product_map <- .double_crop_process_map()
  double_area_map <- .double_crop_area_process_map(crop_prod_items)

  regular_area <- primary_prod |>
    dplyr::filter(.data$unit == "ha") |>
    dplyr::inner_join(crop_prod_items, "item_prod_code") |>
    dplyr::anti_join(
      double_product_map,
      by = c("item_prod_code", "item_cbs_code")
    ) |>
    dplyr::transmute(
      year,
      area_code,
      proc_cbs_code = item_cbs_code,
      crop_area = value
    )

  double_area <- primary_prod |>
    dplyr::filter(.data$unit == "ha") |>
    dplyr::inner_join(
      double_area_map,
      by = c("item_prod_code", "item_cbs_code")
    ) |>
    dplyr::transmute(
      year,
      area_code,
      proc_cbs_code,
      crop_area = value
    )

  dplyr::bind_rows(regular_area, double_area) |>
    dplyr::summarise(
      crop_area = sum(.data$crop_area, na.rm = TRUE),
      .by = c(year, area_code, proc_cbs_code)
    ) |>
    dplyr::filter(.data$crop_area > 0)
}

.build_husbandry <- function(
  husbandry_items,
  feed_intake,
  primary_prod,
  cbs = NULL,
  slaughter_product_items = tibble::tibble(item_cbs_code = integer())
) {
  dplyr::bind_rows(
    .build_use_husbandry(feed_intake),
    .build_supply_husbandry(
      husbandry_items,
      primary_prod,
      cbs,
      slaughter_product_items
    ),
  ) |>
    dplyr::mutate(proc_group = "husbandry")
}

.build_use_husbandry <- function(feed_intake) {
  feed_intake |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = live_anim_code,
      item_cbs_code,
      value = supply
    ) |>
    dplyr::mutate(type = "use")
}

.build_supply_husbandry <- function(
  husbandry_items,
  primary_prod,
  cbs = NULL,
  slaughter_product_items = tibble::tibble(item_cbs_code = integer())
) {
  dplyr::bind_rows(
    .build_livestock_supply(
      primary_prod,
      husbandry_items,
      cbs
    ),
    .build_livestock_prods_supply(
      primary_prod,
      husbandry_items,
      slaughter_product_items
    ),
  ) |>
    dplyr::mutate(type = "supply")
}

.build_livestock_supply <- function(
  primary_prod,
  husbandry_items,
  cbs = NULL
) {
  force(cbs)

  # Feed intake is stock-based, so live-animal husbandry output must use the
  # stock count. CBS production is a slaughter/production flow for these items.
  primary_prod |>
    dplyr::filter(unit == "heads") |>
    dplyr::inner_join(
      husbandry_items,
      dplyr::join_by(item_cbs_code == live_anim_code)
    ) |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = item_cbs_code,
      item_cbs_code = item_cbs_code,
      value
    )
}

.build_animal_draught_supply <- function(
  primary_prod,
  draft_items = tibble::tibble(live_anim_code = integer()),
  animal_draught_item_code = integer()
) {
  if (
    length(animal_draught_item_code) == 0L ||
      nrow(draft_items) == 0L
  ) {
    return(.empty_supply_use_rows())
  }

  draft_items <- .add_animal_draught_work_hours(draft_items)

  primary_prod |>
    dplyr::filter(unit == "LU") |>
    dplyr::inner_join(
      draft_items,
      dplyr::join_by(item_cbs_code == live_anim_code)
    ) |>
    dplyr::filter(.data$work_hours_day > 0) |>
    dplyr::mutate(
      proc_cbs_code = .data$item_cbs_code,
      value = .data$value *
        .data$work_hours_day *
        .animal_draught_tj_per_lu_hour() *
        365,
      item_cbs_code = as.integer(animal_draught_item_code)
    ) |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code,
      item_cbs_code,
      value
    )
}

.build_animal_draught <- function(
  primary_prod,
  draft_items = tibble::tibble(live_anim_code = integer()),
  animal_draught_item_code = integer()
) {
  .build_animal_draught_supply(
    primary_prod,
    draft_items,
    animal_draught_item_code
  ) |>
    dplyr::mutate(
      type = "supply",
      proc_group = "animal_draught"
    )
}

.build_livestock_prods_supply <- function(
  primary_prod,
  husbandry_items,
  exclude_product_items = tibble::tibble(item_cbs_code = integer())
) {
  excluded_items <- exclude_product_items$item_cbs_code %||% integer()

  primary_prod |>
    dplyr::filter(
      unit == "tonnes",
      !item_cbs_code %in% excluded_items
    ) |>
    dplyr::inner_join(husbandry_items, "live_anim_code") |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = live_anim_code,
      item_cbs_code,
      value
    )
}

.build_slaughtering <- function(
  slaughter_items,
  slaughter_product_items,
  cbs,
  primary_prod
) {
  required_cbs <- c(
    "year",
    "area_code",
    "item_cbs_code",
    "processing"
  )
  if (
    nrow(slaughter_items) == 0L ||
      nrow(slaughter_product_items) == 0L ||
      is.null(cbs) ||
      !all(required_cbs %in% names(cbs))
  ) {
    return(.empty_supply_use_rows())
  }

  slaughter_supply <- primary_prod |>
    dplyr::filter(
      unit == "tonnes",
      !is.na(live_anim_code)
    ) |>
    dplyr::inner_join(slaughter_items, "live_anim_code") |>
    dplyr::inner_join(slaughter_product_items, "item_cbs_code") |>
    dplyr::summarise(
      value = sum(value, na.rm = TRUE),
      .by = c(year, area_code, live_anim_code, item_cbs_code)
    ) |>
    dplyr::transmute(
      year,
      area_code,
      proc_cbs_code = live_anim_code,
      item_cbs_code,
      value,
      type = "supply"
    )

  slaughter_keys <- slaughter_supply |>
    dplyr::distinct(year, area_code, live_anim_code = proc_cbs_code)

  cbs_slaughter <- cbs |>
    dplyr::inner_join(
      slaughter_items,
      dplyr::join_by(item_cbs_code == live_anim_code)
    )

  slaughter_use <- slaughter_keys |>
    dplyr::inner_join(
      cbs_slaughter,
      by = c(
        "year",
        "area_code",
        "live_anim_code" = "item_cbs_code"
      )
    ) |>
    dplyr::transmute(
      year,
      area_code,
      proc_cbs_code = live_anim_code,
      item_cbs_code = live_anim_code,
      value = processing
    ) |>
    dplyr::filter(.data$value > 0) |>
    dplyr::mutate(type = "use")

  dplyr::bind_rows(slaughter_use, slaughter_supply) |>
    dplyr::mutate(proc_group = "slaughtering")
}

.build_processing <- function(coeffs) {
  processing_use <- coeffs |>
    dplyr::distinct(
      year,
      area_code,
      proc_cbs_code = item_cbs_code_to_process,
      item_cbs_code = item_cbs_code_to_process,
      value = value_to_process
    ) |>
    dplyr::mutate(type = "use")

  processing_supply <- coeffs |>
    dplyr::select(
      year,
      area_code,
      proc_cbs_code = item_cbs_code_to_process,
      item_cbs_code = item_cbs_code_processed,
      value = final_value_processed
    ) |>
    dplyr::mutate(type = "supply")

  dplyr::bind_rows(processing_use, processing_supply) |>
    dplyr::mutate(proc_group = "processing")
}

.animal_draught_item_code <- function(items_cbs) {
  item <- items_cbs |>
    dplyr::filter(.data$item_cbs_code == 4000L) |>
    dplyr::pull(.data$item_cbs_code) |>
    unique()
  if (length(item) == 0L) {
    return(integer())
  }
  as.integer(item[[1L]])
}

.add_animal_draught_work_hours <- function(draft_items) {
  if (!"work_hours_day" %in% names(draft_items)) {
    draft_items$work_hours_day <- NA_real_
  }

  draft_items |>
    dplyr::left_join(
      .animal_draught_work_hours(),
      by = "live_anim_code",
      suffix = c("", "_default")
    ) |>
    dplyr::mutate(
      work_hours_day = dplyr::coalesce(
        .data$work_hours_day,
        .data$work_hours_day_default
      )
    ) |>
    dplyr::select(-dplyr::any_of("work_hours_day_default"))
}

.animal_draught_work_hours <- function() {
  tibble::tibble(
    live_anim_code = c(946L, 1096L, 1107L, 1110L, 1126L, 1157L),
    category = c(
      "Buffalo",
      "Horses",
      "Mules and Asses",
      "Mules and Asses",
      "Camels",
      "Camels"
    )
  ) |>
    dplyr::left_join(
      whep::livestock_production_defaults |>
        dplyr::select(category, work_hours_day),
      by = "category"
    ) |>
    dplyr::select(-"category")
}

.animal_draught_tj_per_lu_hour <- function() {
  # Useful work energy from 0.5 kW sustained draught power per livestock unit.
  0.5 * 3.6 / 1e6
}

.empty_supply_use_rows <- function() {
  tibble::tibble(
    year = integer(),
    area_code = integer(),
    proc_cbs_code = integer(),
    item_cbs_code = integer(),
    value = numeric()
  )
}
