# Suppress R CMD check warnings for dplyr NSE (Non Standard Evaluation)
utils::globalVariables(
  c(
    ":=",
    ".data",
    ".source_temp",
    ".smooth_var",
    "ADB_Region",
    "adb_region",
    "agriland",
    "alias",
    "Animal_class",
    "area",
    "area_code",
    "area_code_p",
    "area_ha",
    "area_mha",
    "Area.Code",
    "area_name",
    "Area_Mha",
    "AreaCode",
    "balanced_export",
    "balanced_import",
    "balance",
    "balance2",
    "bilateral_trade",
    "Cat_1",
    "CBS",
    "cf",
    "check",
    "check_fu",
    "check_t",
    "code",
    "comm_group",
    "Cropland",
    "cv",
    "default_destiny",
    "dest_share",
    "dest_share_global",
    "destiny_replacement",
    "distinct",
    "dm",
    "domestic_supply",
    "ds_destinies",
    "ds2",
    "ds3",
    "elem_cat",
    "element",
    "Element",
    "export",
    "export_share",
    "export_val",
    "fbs_comp",
    "FBS_New",
    "FBS_Old",
    "feed",
    "feed_share",
    "feedtype",
    "fill_value",
    "final_value_processed",
    "food",
    "food_share",
    "from_code",
    "fu",
    "fu_mean",
    "fu_sum",
    "fu2",
    "gross_avail",
    "group",
    "groups",
    "ha",
    "ha_euadb",
    "has_np",
    "ha_share",
    "ha_tot",
    "heads",
    "import",
    "Imp/Exp",
    "ind_growth",
    "Info_Format",
    "intake",
    "intake_dm",
    "ISO3",
    "iso3",
    "iso3c",
    "Item.Code",
    "item",
    "Item",
    "Item_Code",
    "Item_area",
    "item_cbs",
    "item_cbs_code",
    "item_cbs_code_crop",
    "item_cbs_code_processed",
    "item_cbs_code_residue",
    "item_cbs_code_to_process",
    "item_cbs_name",
    "item_code",
    "item_code_cbs",
    "item_code_prod",
    "item_code_trade",
    "item_processed",
    "item_prod",
    "item_prod_code",
    "item_prod_name",
    "item_st",
    "item_to_process",
    "item_trade",
    "item_type",
    "ItemCode",
    "ItemName",
    "kgnha_euadb",
    "Label",
    "lag_src",
    "lag_yr",
    "land_use",
    "Land_Use",
    "Live_anim",
    "Live_anim_code",
    "live_anim_code",
    "Livestock_name",
    "LU",
    "LU_head",
    "loss",
    "loss_share",
    "ma_base",
    "measurement",
    "min_scaling",
    "Multi_type",
    "multi_type",
    "n",
    "Name",
    "Name_biomass",
    "Name_Eurostat",
    "net_bal1",
    "net_bal2",
    "net_export",
    "net_import",
    "net_trade",
    "No",
    "other_uses",
    "other_uses_share",
    "Palm_kernels",
    "Palmkernel_Oil",
    "Pasture",
    "polity_code",
    "polity_name",
    "pop",
    "prefilled",
    "Primary",
    "proc",
    "proc_cbs_code",
    "proc_group",
    "proc_scaling",
    "process",
    "processed_item",
    "ProcessedItem",
    "processing",
    "processing_primary",
    "processing_primary_share",
    "processing_share",
    "prod_calc",
    "prod_cbs_count",
    "prod_cbs_ratio",
    "prod_ygpit_mg",
    "product_fraction",
    "Product_fraction",
    "Product_kgDM_kgFM",
    "Product_kgN_kgDM",
    "product_residue",
    "production",
    "proxy_ratio",
    "Region",
    "reclassified_value",
    "remove",
    "Required",
    "required",
    "SACO_link",
    "scaling",
    "scaling_raw",
    "sd",
    "seed",
    "seed_rate",
    "sex",
    "share",
    "source",
    "Source",
    "source_scaling_raw",
    "source_value",
    "stock_variation",
    "sum_dests",
    "sum_ha",
    "sumprod_cbs_ratio",
    "supply",
    "t",
    "t_2",
    "t_cbs",
    "t_dm",
    "t_dmbased",
    "t_euadb",
    "t_ha",
    "t_ha_raw",
    "t_head",
    "t_LU",
    "t2",
    "Timeline_End",
    "Timeline_Freq",
    "Timeline_Start",
    "to_code",
    "tonnes",
    "total_export",
    "total_import",
    "total_trade",
    "Trade",
    "type",
    "Unit",
    "unit",
    "value",
    "Value",
    "value_agriland",
    "value_carried_backward",
    "value_carried_forward",
    "value_comb",
    "value_cropland",
    "value_final",
    "value_final_old",
    "value_interpfilled",
    "value_livestockyield",
    "value_lu",
    "value_proc",
    "value_proc_raw",
    "value_scaling",
    "value_sel",
    "value_st",
    "value_to_process",
    "value2",
    "Value_fraction",
    "w",
    "year",
    "Year",
    "yield",
    "yield_c",
    "yield_dm",
    "yield_glo",
    # clean_faostat.R / build_v2.R QC helpers
    ".anchor", ".anchor_start", ".from_end", ".intercept", ".is_cf",
    ".last_val", ".n_anchor", ".prev", ".ratio", ".run_length",
    ".slope", ".smoothed", ".time", ".use_anchor", ".val",
    "qc_carry_forward",
    # livestock emission functions
    "adjustment_factor", "ash_percent", "Bo", "bo_category",
    "bo_m3_kg_vs", "Ca", "ca_feedlot", "ca_pasture", "category",
    "cfi_mj_day_kg075", "climate_zone", "cohort", "cohort_share",
    "cp", "cp_percent", "cw", "DE_percent", "de_percent",
    "de_percent_feed", "defaults_key",
    "diet_quality", "ef3", "ef_cattle", "ef_global",
    "ef_kg_head_yr", "ef_kg_n2o_n_per_kg_n", "ef_other",
    "energy_content_gain_mj_kg", "enteric_ch4_per_head",
    "enteric_ef_kgch4", "fat_percent", "fat_percent_default",
    "fraction", "GE", "gleam_region", "grazing_distance_km",
    "lactose_percent", "lactose_percent_default",
    "manure_category", "manure_ch4_per_head", "manure_ef_kgch4",
    "manure_n2o_direct", "manure_n2o_indirect", "mcf_percent",
    "Method_Energy", "Method_Manure_CH4", "milk_yield_kg_day",
    "mms_type", "N_intake", "n_cohorts", "n_ret_category",
    "n_retention_frac", "n2o_leaching", "n2o_volatilization",
    "ndf_percent", "NE_growth", "NE_maintenance", "NEa", "NEg",
    "NEl", "NEm", "NEp", "NEwool", "NEwork", "Nex", "parameter",
    "pregnant_fraction", "pregnant_fraction_default",
    "production_system", "protein_percent",
    "protein_percent_default", "REG", "REM", "region", "row_id",
    "row_id_n2o", "species", "species_base", "species_gen",
    "subcategory", "temp_adjustment", "temp_max", "temp_min",
    "temperature_c", "VS", "weight", "weight_gain_kg_day",
    "weight_gain_kg_day_default", "weight_kg",
    "weight_kg_global", "weighted_ef3", "weighted_mcf",
    "wool_production_kg_yr", "work_hours_day",
    "work_hours_day_default", "Ym", "ym_percent",
    "all_categories", "cohort_fraction", "system_share"
  )
)
