# Suppress R CMD check warnings for dplyr NSE (Non Standard Evaluation)
utils::globalVariables(
  c(
    "cf",
    "element",
    "Element",
    "Imp/Exp",
    "Info_Format",
    "item",
    "Item",
    "item_code",
    "Name",
    "No",
    "processeditem",
    "product_fraction",
    "SACO_link",
    "scaling",
    "sex",
    "stock_variation",
    "Timeline_End",
    "Timeline_Freq",
    "Timeline_Start",
    "Trade",
    "value",
    "Value",
    "value_proc",
    "value_proc_raw",
    "Year"
  )
)
